#!/bin/sh
pwd
python2 /home/mateusz/Studies/AGH_sem_10/mgr/workflows/montage2-workflow/workflow-generator/montage-workflow.py "$@" && hflow-convert-dax data/montage.dax > workflow.json && rm data/montage.dax
